### ISSUE TITLE
Test Key Handling

### ISSUE THREAD

**Issue by FreneticScribbler** [tiesjan/django-hcaptcha-field#1] opened 2021-09-18 08:44 UTC
Thanks for making the switch to hCaptcha super smooth in my project! Just one minor bump...when running automated tests, hCaptcha provides a set of test keys that don't seem to be accounted for in the form field validator. 

I lazily patched it to just skip all validation if the test key is in use, but to do it 'properly' you may want to validate that the test response is produced.

https://docs.hcaptcha.com/#integration-testing-test-keys

**Comment by tiesjan** [comment] 2021-09-20 09:45
Thank you for raising this issue, @FreneticScribbler.

In my understanding, the purpose of test keys is to fully integrate hCaptcha without actually challenging the visitor. Apart from being (obviously) impossible to solve challenges in automated tests, you are outsourcing them to hCaptcha and thus not your responsibility to test. The test keys allow you to bypass them in automated tests or when working in development environments, for example. It also allows developers to try out this package without the need for a proper set of hCaptcha keys, due to defaulting to the test keys.

That being said, I also understand there's a wish to not always have a request made to the hCaptcha servers. This can really slow down automated tests. So far my stance has been that developers can deal with this themselves, which is why I myself [mocked responses](https://github.com/tiesjan/django-hcaptcha-field/blob/main/py_tests/conftest.py) in automated tests of this forked package and why someone else opened [this pull request](https://github.com/AndrejZbin/django-hcaptcha/pull/6) for the original package.

So yeah, it's a very valid point you're raising, but as you can see bypassing validation has its pros and cons. Perhaps I can introduce an `HCAPTCHA_SKIP_TEST_KEYS_VERIFICATION` setting that can be set as preferred by developers. Would that help you out in this?

**Comment by FreneticScribbler** [comment] 2021-09-21 10:20
With test keys in use I am unable to get the validation to pass. Sounds like this is my error, though, if it works for you...

**Comment by tiesjan** [comment] 2021-09-23 08:07
I can confirm it indeed works for me. Let me know if there's something I can help you out with.

Closing this issue for now.

**Closed as completed by tiesjan** 2021-09-23 08:07 UTC
